version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "blyedev"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "blyedev"
    labels:
      - "backend"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "blyedev"
    labels:
      - "backend"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "blyedev"
    labels:
      - "frontend"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "blyedev"
    labels:
      - "frontend"
      - "dependencies"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
          - "angular-eslint"
        update-types:
          - "minor"
          - "patch"
      minor-and-patch:
        applies-to: security-updates
        patterns:
          - "@angular*"
          - "angular-eslint"
        update-types:
          - "patch"
          - "minor"
      eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
