version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "frontend"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "frontend"
      - "dependencies"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      minor-and-patch:
        applies-to: security-updates
        patterns:
        - "@angular*"
        update-types:
        - "patch"
        - "minor"
      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
