version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "backend"
      - "dependencies"
    group:
      name: "backend-poetry-dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "frontend"
      - "dependencies"
    group:
      name: "frontend-npm-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    labels:
      - "ci"
      - "dependencies"
    group:
      name: "github-actions-dependencies"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "backend"
      - "docker"
    group:
      name: "backend-docker-dependencies"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "frontend"
      - "docker"
    group:
      name: "frontend-docker-dependencies"
