services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
    ports:
      - "4200:4200"
