version: '3.8'

include:
  - ./backend/compose.dev.yml
  - ./frontend/compose.dev.yml

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
      - angular 
    logging:
      driver: "none"
