services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password

  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: on-failure:3
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
        - path: ./pyproject.toml
          action: rebuild
        - path: ./poetry.lock
          action: rebuild
        - path: ./calendar_project/settings.py
          action: sync+restart
          target: ./app/calendar_project/settings.py
        - path: ./
          action: sync
          target: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_EMAIL=adam.smielewski@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=root
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
