services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password

  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./pyproject.toml
          action: rebuild
        - path: ./poetry.lock
          action: rebuild
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_EMAIL=adam.smielewski@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=Ziomek56
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
