# Generated by Django 4.2.5 on 2023-09-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('treenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.treenode')),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
            ],
            bases=('api.treenode',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('treenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.treenode')),
            ],
            bases=('api.treenode',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('treenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.treenode')),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
            ],
            bases=('api.treenode',),
        ),
    ]
