services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
        - path: ./nginx.conf
          action: sync+restart
          target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
      - angular
