services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    develop:
      watch:
        - path: ./nginx.conf
          action: sync+restart
          target: /etc/nginx/nginx.conf
    depends_on:
      - django
      - angular
