name: CI Checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend_checks:
    name: Frontend CI
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Type Check
        run: tsc

      - name: Run Ng Lint
        run: npm run lint:ng:ci

      - name: Run Stylelint
        run: npm run lint:css:ci

      - name: Run Prettier check
        run: npm run prettier:check

  backend_checks:
    name: Backend CI
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked

      - name: Run MyPy Static Typing Check
        run: uv run mypy .

      - name: Run Ruff Linter
        run: uv run ruff check --output-format=github .

      - name: Run Ruff Formatter
        run: uv run ruff format --check

  hadolint:
    name: Dockerfiles CI
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: Dockerfile
          recursive: true
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
